language: java
jdk:
- oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
after_success:
- mvn clean cobertura:cobertura coveralls:report
env:
  global:
    secure: iuZTrfnJJRaqAD8IRiW38jkxIP1Gcjvrw+Vf29kYm2s789MJxM/YfYxOqQmoxvoNXolC3fDfb+V45I7zPkvxBJ1MJhq5wPtaSmzxnjEUeqTJSxf4P4k9EaEEpMfc9UFlVOzdfrE21FRnACK1s0b3CN8Ma08z+sJAxsKzugFCuc+hoCeBo0LXEotzB9bbUU4UAOtLfcprJw5XO2rX193bNv+2IcEJMUR57ILSdvwTE5CIKjhx4BkG38uibwLOjn5uEdisIGI8Q8JrBUFgEayUyO20BSTh4Jnza1+ocxuTHW4SSVjSg8rpYuwXkWs6vzivFR/9vmKmAWz1VhjTNN3ct+Kbj9NCguTDkQDnJYbYkEyJ1JTu3Lwq2KEWLwz1ov/u3F8ZQjUPnFwrDG09EK8a/Jclp0UTrtY0q/lTVZKkYevurGx6QQW7V5a26+rIbux4sp4h6xUfe7Sqnh3FGG5orfzc5tzERbNSixrjKz192cwFebFfBs/P0iNGWXMUUje1l/7RcK2l0LweSKcwRoyj2m/0JhIEamdwBWH3MpZPaLNTpDMd6x3K1J6gecJGJC6J2M+EAotMb+cPkXAN0PJvkzoB6Qe2Nei4EEDzTGJRNKV3+cqV5hXbakO+HJ3s1y1KuQXMOmyYjv9txWJxYmBsXrdU08Al9wujnP6JZn0Z6nc=
